services:
  backend:
    build:
      context: ./ssm-admin-backend
      dockerfile: Dockerfile
    image: ssm-admin-backend:latest
    container_name: ssm-backend
    restart: always
    expose:
      - "8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ssm-network

  frontend:
    build:
      context: .
      dockerfile: ./soybean-admin/Dockerfile
    image: ssm-vue-deploy-frontend:latest
    container_name: vue-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ssm-network

networks:
  ssm-network:
    external: true