jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://82.156.142.135:3306/SSM_project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
jdbc.username=root
jdbc.password=Ly17638732656@